In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
#loading the messy data
df = pd.read_csv('logistics.csv')
df

NameError: name 'pd' is not defined

# 2. Initial inspection (ALWAYS do this first!)

In [ ]:
print(df.head())

   OrderID   CustomerName Region  ShipMode   OrderDate    ShipDate  \
0     1001  Alice Johnson  North   Express  2024-01-03  2024-01-05   
1     1002      Bob Smith  South  Standard  2024-01-04  2024-01-08   
2     1003    Carol White   East   Express  2024-01-05  2024-01-07   
3     1004    David Brown   West   Economy  2024-01-06  2024-01-12   
4     1005      Eva Green  North  Standard  2024-01-07  2024-01-11   

   DeliveryDays  Weight(kg)  Distance(km)  ShippingCost     Status  
0             2         5.2           120          45.0  Delivered  
1             4        12.0           340          30.0  Delivered  
2             2         3.1            90          40.0    Delayed  
3             6        20.5           500          20.0  Delivered  
4             4         8.0           210          28.0    Delayed  


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   OrderID       20 non-null     int64  
 1   CustomerName  20 non-null     object 
 2   Region        20 non-null     object 
 3   ShipMode      20 non-null     object 
 4   OrderDate     20 non-null     object 
 5   ShipDate      20 non-null     object 
 6   DeliveryDays  20 non-null     int64  
 7   Weight(kg)    20 non-null     float64
 8   Distance(km)  20 non-null     int64  
 9   ShippingCost  20 non-null     float64
 10  Status        20 non-null     object 
dtypes: float64(2), int64(3), object(6)
memory usage: 1.8+ KB
None


In [ ]:
print(df.isnull().sum())

OrderID         0
CustomerName    0
Region          0
ShipMode        0
OrderDate       0
ShipDate        0
DeliveryDays    0
Weight(kg)      0
Distance(km)    0
ShippingCost    0
Status          0
dtype: int64


In [ ]:
x = df.iloc[:, [2, 3, 6, 7, 8, 9]].values
y = df.iloc[:, -1].values

In [ ]:
print(x)

[['North' 'Express' 2 5.2 120 45.0]
 ['South' 'Standard' 4 12.0 340 30.0]
 ['East' 'Express' 2 3.1 90 40.0]
 ['West' 'Economy' 6 20.5 500 20.0]
 ['North' 'Standard' 4 8.0 210 28.0]
 ['South' 'Express' 2 6.5 150 43.0]
 ['East' 'Economy' 6 15.0 420 18.0]
 ['West' 'Standard' 4 9.2 270 31.0]
 ['North' 'Express' 2 4.0 100 42.0]
 ['South' 'Economy' 6 22.0 600 17.0]
 ['East' 'Standard' 4 7.5 190 29.0]
 ['West' 'Express' 2 5.0 130 44.0]
 ['North' 'Economy' 6 18.0 480 19.0]
 ['South' 'Standard' 4 11.0 310 32.0]
 ['East' 'Express' 2 3.8 85 41.0]
 ['West' 'Economy' 6 25.0 650 16.0]
 ['North' 'Standard' 4 9.8 230 30.0]
 ['South' 'Express' 2 6.0 140 43.0]
 ['East' 'Economy' 6 19.5 520 18.0]
 ['West' 'Standard' 4 8.5 200 29.0]]


In [ ]:
print (y)

['Delivered' 'Delivered' 'Delayed' 'Delivered' 'Delayed' 'Delivered'
 'Lost' 'Delivered' 'Delivered' 'Delayed' 'Delivered' 'Delivered'
 'Delayed' 'Delivered' 'Delivered' 'Lost' 'Delivered' 'Delayed'
 'Delivered' 'Delivered']


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print (x)

[[0.0 1.0 0.0 0.0 0.0 1.0 0.0 2 5.2 120 45.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 4 12.0 340 30.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 2 3.1 90 40.0]
 [0.0 0.0 0.0 1.0 1.0 0.0 0.0 6 20.5 500 20.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 4 8.0 210 28.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 2 6.5 150 43.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 6 15.0 420 18.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 1.0 4 9.2 270 31.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 2 4.0 100 42.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 6 22.0 600 17.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 4 7.5 190 29.0]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 2 5.0 130 44.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 6 18.0 480 19.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 4 11.0 310 32.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 2 3.8 85 41.0]
 [0.0 0.0 0.0 1.0 1.0 0.0 0.0 6 25.0 650 16.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 4 9.8 230 30.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 2 6.0 140 43.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 6 19.5 520 18.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 1.0 4 8.5 200 29.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(y)
print(Y)

[1 1 0 1 0 1 2 1 1 0 1 1 0 1 1 2 1 0 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, X_test, y_train, y_test = train_test_split(x, Y, test_size=0.2, random_state=24)

In [ ]:
from sklearn.model_selection import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

ImportError: cannot import name 'LinearRegression' from 'sklearn.model_selection' (/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/__init__.py)